### ISSUE TITLE
Change Vault implementation to use more than KV secrets engine

### ISSUE THREAD

**Issue by shankj3** [shankj3/ocelot#78]
As of now, ocelot only uses the key value secrets engine. We should be using the appropriate secrets engine for secret type. 

At the very least: 
[database engine](https://www.vaultproject.io/docs/secrets/databases/postgresql.html) for postgres retrieval 

---
this should be accompanied by an update of [go-til](https://github.com/shankj3/go-til)'s Vault implementation to also include token renewal. Using non-expiring tokens is just silly. When a new  instance of remoteConfig is instantiated, a thread should be kicked off to renew on an interval.

**Comment by tjtelan** [comment]
We will need to add another config key in consul so we can switch between Vault's default KV secrets, and Database secret engine.

(I'm completely lacking imagination here, so this keyname might change)

Consul path:
`config/ocelot/postgres/vaultsecrettype kv` # Which will probably be the default
`config/ocelot/postgres/vaultsecrettype database` # Which will use the Vault database secrets engine

**Comment by tjtelan** [comment]
Leaving this here, but this should be documented in docs for setting up the Vault database engine.

Vault tries to connect to Postgresql using SSL by default. You can override this behavior by adding the `?sslmode=disable` parameter in your connection url

##### Modified from Vault docs
    $ vault write database/config/my-postgresql-database \
        plugin_name=postgresql-database-plugin \
        allowed_roles="my-role" \
        connection_url="postgresql://{{username}}:{{password}}@localhost:5432/?sslmode=disable" \
        username="root" \
        password="root"
